interface ZIF_DEV_SALESORDER_TX_C
  public .


  interfaces /BOBF/IF_LIB_CONSTANTS .

  constants:
    BEGIN OF SC_ACTION,
      BEGIN OF ZDEV_SALESORDER_TX,
 CREATE_ZDEV_SALESORDER_TX      TYPE /BOBF/ACT_KEY VALUE '288023A883C01ED8ADD3C2CC26D179DA',
 DELETE_ZDEV_SALESORDER_TX      TYPE /BOBF/ACT_KEY VALUE '288023A883C01ED8ADD3C2CC26D1F9DA',
 LOCK_ZDEV_SALESORDER_TX        TYPE /BOBF/ACT_KEY VALUE '288023A883C01ED8ADD3C2CC26D0B9DA',
 SAVE_ZDEV_SALESORDER_TX        TYPE /BOBF/ACT_KEY VALUE '288023A883C01ED8ADD3C2CC26D279DA',
 SET_TO_PAID                    TYPE /BOBF/ACT_KEY VALUE '288023A883C01ED8ADD3E595D219DAEB',
 UNLOCK_ZDEV_SALESORDER_TX      TYPE /BOBF/ACT_KEY VALUE '288023A883C01ED8ADD3C2CC26D0F9DA',
 UPDATE_ZDEV_SALESORDER_TX      TYPE /BOBF/ACT_KEY VALUE '288023A883C01ED8ADD3C2CC26D1B9DA',
 VALIDATE_ZDEV_SALESORDER_TX    TYPE /BOBF/ACT_KEY VALUE '288023A883C01ED8ADD3C2CC26D239DA',
      END OF ZDEV_SALESORDER_TX,
    END OF SC_ACTION .
  constants:
    BEGIN OF SC_ACTION_ATTRIBUTE,
        BEGIN OF ZDEV_SALESORDER_TX,
        BEGIN OF LOCK_ZDEV_SALESORDER_TX,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
        END OF LOCK_ZDEV_SALESORDER_TX,
        BEGIN OF UNLOCK_ZDEV_SALESORDER_TX,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
        END OF UNLOCK_ZDEV_SALESORDER_TX,
      END OF ZDEV_SALESORDER_TX,
    END OF SC_ACTION_ATTRIBUTE .
  constants:
    BEGIN OF SC_ALTERNATIVE_KEY,
      BEGIN OF ZDEV_SALESORDER_TX,
 DB_KEY                         TYPE /BOBF/OBM_ALTKEY_KEY VALUE '288023A883C01ED8ADD3C59E0FD0D9FB',
      END OF ZDEV_SALESORDER_TX,
    END OF SC_ALTERNATIVE_KEY .
  constants:
    BEGIN OF SC_ASSOCIATION,
      BEGIN OF ZDEV_SALESORDER_TX,
 LOCK                           TYPE /BOBF/OBM_ASSOC_KEY VALUE '288023A883C01ED8ADD3C2CC26D099DA',
 MESSAGE                        TYPE /BOBF/OBM_ASSOC_KEY VALUE '288023A883C01ED8ADD3C2CC26D059DA',
 PROPERTY                       TYPE /BOBF/OBM_ASSOC_KEY VALUE '288023A883C01ED8ADD3C2CC26D159DA',
      END OF ZDEV_SALESORDER_TX,
      BEGIN OF ZDEV_SALESORDER_TX_LOCK,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '288023A883C01ED8ADD3C2CC26D2D9DA',
      END OF ZDEV_SALESORDER_TX_LOCK,
      BEGIN OF ZDEV_SALESORDER_TX_MESSAGE,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '288023A883C01ED8ADD3C2CC26D2B9DA',
      END OF ZDEV_SALESORDER_TX_MESSAGE,
      BEGIN OF ZDEV_SALESORDER_TX_PROPERTY,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '288023A883C01ED8ADD3C2CC26D2F9DA',
      END OF ZDEV_SALESORDER_TX_PROPERTY,
    END OF SC_ASSOCIATION .
  constants:
    BEGIN OF SC_ASSOCIATION_ATTRIBUTE,
      BEGIN OF ZDEV_SALESORDER_TX,
        BEGIN OF PROPERTY,
 ALL_NODE_PROPERTY              TYPE STRING VALUE 'ALL_NODE_PROPERTY',
 ALL_NODE_ATTRIBUTE_PROPERTY    TYPE STRING VALUE 'ALL_NODE_ATTRIBUTE_PROPERTY',
 ALL_ASSOCIATION_PROPERTY       TYPE STRING VALUE 'ALL_ASSOCIATION_PROPERTY',
 ALL_ASSOCIATION_ATTRIBUTE_PROP TYPE STRING VALUE 'ALL_ASSOCIATION_ATTRIBUTE_PROP',
 ALL_ACTION_PROPERTY            TYPE STRING VALUE 'ALL_ACTION_PROPERTY',
 ALL_ACTION_ATTRIBUTE_PROPERTY  TYPE STRING VALUE 'ALL_ACTION_ATTRIBUTE_PROPERTY',
 ALL_QUERY_PROPERTY             TYPE STRING VALUE 'ALL_QUERY_PROPERTY',
 ALL_QUERY_ATTRIBUTE_PROPERTY   TYPE STRING VALUE 'ALL_QUERY_ATTRIBUTE_PROPERTY',
 ALL_SUBTREE_PROPERTY           TYPE STRING VALUE 'ALL_SUBTREE_PROPERTY',
        END OF PROPERTY,
      END OF ZDEV_SALESORDER_TX,
    END OF SC_ASSOCIATION_ATTRIBUTE .
  constants:
    SC_BO_KEY  TYPE /BOBF/OBM_BO_KEY VALUE '288023A883C01ED8ADD3C2CC26CFB9DA' .
  constants:
    SC_BO_NAME TYPE /BOBF/OBM_NAME VALUE 'ZDEV_SALESORDER_TX' .
  constants:
    BEGIN OF SC_DETERMINATION,
      BEGIN OF ZDEV_SALESORDER_TX,
 ACTION_AND_FIELD_CONTROL       TYPE /BOBF/DET_KEY VALUE '288023A883C01ED8ADD3C59E0FD0F9FB',
      END OF ZDEV_SALESORDER_TX,
    END OF SC_DETERMINATION .
  constants:
    SC_MODEL_VERSION TYPE /BOBF/CONF_VERSION VALUE '00000' .
  constants:
    BEGIN OF SC_NODE,
 ZDEV_SALESORDER_TX             TYPE /BOBF/OBM_NODE_KEY VALUE '288023A883C01ED8ADD3C2CC26CFF9DA',
 ZDEV_SALESORDER_TX_LOCK        TYPE /BOBF/OBM_NODE_KEY VALUE '288023A883C01ED8ADD3C2CC26D079DA',
 ZDEV_SALESORDER_TX_MESSAGE     TYPE /BOBF/OBM_NODE_KEY VALUE '288023A883C01ED8ADD3C2CC26D039DA',
 ZDEV_SALESORDER_TX_PROPERTY    TYPE /BOBF/OBM_NODE_KEY VALUE '288023A883C01ED8ADD3C2CC26D139DA',
    END OF SC_NODE .
  constants:
    BEGIN OF SC_NODE_ATTRIBUTE,
      BEGIN OF ZDEV_SALESORDER_TX,
  NODE_DATA                      TYPE STRING VALUE 'NODE_DATA',
  SALESORDER                     TYPE STRING VALUE 'SALESORDER',
  BUSINESSPARTNER                TYPE STRING VALUE 'BUSINESSPARTNER',
  CURRENCYCODE                   TYPE STRING VALUE 'CURRENCYCODE',
  GROSSAMOUNT                    TYPE STRING VALUE 'GROSSAMOUNT',
  NETAMOUNT                      TYPE STRING VALUE 'NETAMOUNT',
  BILLINGSTATUS                  TYPE STRING VALUE 'BILLINGSTATUS',
  OVERALLSTATUS                  TYPE STRING VALUE 'OVERALLSTATUS',
  CREA_DATE_TIME                 TYPE STRING VALUE 'CREA_DATE_TIME',
  CREA_UNAME                     TYPE STRING VALUE 'CREA_UNAME',
  LCHG_DATE_TIME                 TYPE STRING VALUE 'LCHG_DATE_TIME',
  LCHG_UNAME                     TYPE STRING VALUE 'LCHG_UNAME',
      END OF ZDEV_SALESORDER_TX,
    END OF SC_NODE_ATTRIBUTE .
  constants:
    BEGIN OF SC_NODE_CATEGORY,
      BEGIN OF ZDEV_SALESORDER_TX,
 ROOT                           TYPE /BOBF/OBM_NODE_CAT_KEY VALUE '288023A883C01ED8ADD3C2CC26D019DA',
      END OF ZDEV_SALESORDER_TX,
    END OF SC_NODE_CATEGORY .
endinterface.
