interface ZIF_S4H_INVOICE_TP_C
  public .


  interfaces /BOBF/IF_LIB_CONSTANTS .

  constants:
    BEGIN OF SC_ACTION,
      BEGIN OF ZS4H_INVOICE_TP,
 CREATE_ZS4H_INVOICE_TP         TYPE /BOBF/ACT_KEY VALUE '288023A883C01EE8A9D49B38BEB6A5CE',
 DELETE_ZS4H_INVOICE_TP         TYPE /BOBF/ACT_KEY VALUE '288023A883C01EE8A9D49B38BEB725CE',
 LOCK_ZS4H_INVOICE_TP           TYPE /BOBF/ACT_KEY VALUE '288023A883C01EE8A9D49B38BEB5E5CE',
 SAVE_ZS4H_INVOICE_TP           TYPE /BOBF/ACT_KEY VALUE '288023A883C01EE8A9D49B38BEB7A5CE',
 SET_TO_PAID                    TYPE /BOBF/ACT_KEY VALUE '288023A883C01EE8A9D613EF6BAD533F',
 UNLOCK_ZS4H_INVOICE_TP         TYPE /BOBF/ACT_KEY VALUE '288023A883C01EE8A9D49B38BEB625CE',
 UPDATE_ZS4H_INVOICE_TP         TYPE /BOBF/ACT_KEY VALUE '288023A883C01EE8A9D49B38BEB6E5CE',
 VALIDATE_ZS4H_INVOICE_TP       TYPE /BOBF/ACT_KEY VALUE '288023A883C01EE8A9D49B38BEB765CE',
      END OF ZS4H_INVOICE_TP,
    END OF SC_ACTION .
  constants:
    BEGIN OF SC_ACTION_ATTRIBUTE,
        BEGIN OF ZS4H_INVOICE_TP,
        BEGIN OF LOCK_ZS4H_INVOICE_TP,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
        END OF LOCK_ZS4H_INVOICE_TP,
        BEGIN OF UNLOCK_ZS4H_INVOICE_TP,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
        END OF UNLOCK_ZS4H_INVOICE_TP,
      END OF ZS4H_INVOICE_TP,
    END OF SC_ACTION_ATTRIBUTE .
  constants:
    BEGIN OF SC_ALTERNATIVE_KEY,
      BEGIN OF ZS4H_INVOICE_TP,
 DB_KEY                         TYPE /BOBF/OBM_ALTKEY_KEY VALUE '288023A883C01EE8A9D49B5A260BC5CE',
      END OF ZS4H_INVOICE_TP,
    END OF SC_ALTERNATIVE_KEY .
  constants:
    BEGIN OF SC_ASSOCIATION,
      BEGIN OF ZS4H_INVOICE_TP,
 LOCK                           TYPE /BOBF/OBM_ASSOC_KEY VALUE '288023A883C01EE8A9D49B38BEB5C5CE',
 MESSAGE                        TYPE /BOBF/OBM_ASSOC_KEY VALUE '288023A883C01EE8A9D49B38BEB585CE',
 PROPERTY                       TYPE /BOBF/OBM_ASSOC_KEY VALUE '288023A883C01EE8A9D49B38BEB685CE',
      END OF ZS4H_INVOICE_TP,
      BEGIN OF ZS4H_INVOICE_TP_LOCK,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '288023A883C01EE8A9D49B38BEB805CE',
      END OF ZS4H_INVOICE_TP_LOCK,
      BEGIN OF ZS4H_INVOICE_TP_MESSAGE,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '288023A883C01EE8A9D49B38BEB7E5CE',
      END OF ZS4H_INVOICE_TP_MESSAGE,
      BEGIN OF ZS4H_INVOICE_TP_PROPERTY,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '288023A883C01EE8A9D49B38BEB825CE',
      END OF ZS4H_INVOICE_TP_PROPERTY,
    END OF SC_ASSOCIATION .
  constants:
    BEGIN OF SC_ASSOCIATION_ATTRIBUTE,
      BEGIN OF ZS4H_INVOICE_TP,
        BEGIN OF PROPERTY,
 ALL_NODE_PROPERTY              TYPE STRING VALUE 'ALL_NODE_PROPERTY',
 ALL_NODE_ATTRIBUTE_PROPERTY    TYPE STRING VALUE 'ALL_NODE_ATTRIBUTE_PROPERTY',
 ALL_ASSOCIATION_PROPERTY       TYPE STRING VALUE 'ALL_ASSOCIATION_PROPERTY',
 ALL_ASSOCIATION_ATTRIBUTE_PROP TYPE STRING VALUE 'ALL_ASSOCIATION_ATTRIBUTE_PROP',
 ALL_ACTION_PROPERTY            TYPE STRING VALUE 'ALL_ACTION_PROPERTY',
 ALL_ACTION_ATTRIBUTE_PROPERTY  TYPE STRING VALUE 'ALL_ACTION_ATTRIBUTE_PROPERTY',
 ALL_QUERY_PROPERTY             TYPE STRING VALUE 'ALL_QUERY_PROPERTY',
 ALL_QUERY_ATTRIBUTE_PROPERTY   TYPE STRING VALUE 'ALL_QUERY_ATTRIBUTE_PROPERTY',
 ALL_SUBTREE_PROPERTY           TYPE STRING VALUE 'ALL_SUBTREE_PROPERTY',
        END OF PROPERTY,
      END OF ZS4H_INVOICE_TP,
    END OF SC_ASSOCIATION_ATTRIBUTE .
  constants:
    SC_BO_KEY  TYPE /BOBF/OBM_BO_KEY VALUE '288023A883C01EE8A9D49B38BEB4E5CE' .
  constants:
    SC_BO_NAME TYPE /BOBF/OBM_NAME VALUE 'ZS4H_INVOICE_TP' .
  constants:
    BEGIN OF SC_DETERMINATION,
      BEGIN OF ZS4H_INVOICE_TP,
 ACTION_AND_FIELD_CONTROL       TYPE /BOBF/DET_KEY VALUE '288023A883C01EE8A9D49B5A260BE5CE',
      END OF ZS4H_INVOICE_TP,
    END OF SC_DETERMINATION .
  constants:
    SC_MODEL_VERSION TYPE /BOBF/CONF_VERSION VALUE '00000' .
  constants:
    BEGIN OF SC_NODE,
 ZS4H_INVOICE_TP                TYPE /BOBF/OBM_NODE_KEY VALUE '288023A883C01EE8A9D49B38BEB525CE',
 ZS4H_INVOICE_TP_LOCK           TYPE /BOBF/OBM_NODE_KEY VALUE '288023A883C01EE8A9D49B38BEB5A5CE',
 ZS4H_INVOICE_TP_MESSAGE        TYPE /BOBF/OBM_NODE_KEY VALUE '288023A883C01EE8A9D49B38BEB565CE',
 ZS4H_INVOICE_TP_PROPERTY       TYPE /BOBF/OBM_NODE_KEY VALUE '288023A883C01EE8A9D49B38BEB665CE',
    END OF SC_NODE .
  constants:
    BEGIN OF SC_NODE_ATTRIBUTE,
      BEGIN OF ZS4H_INVOICE_TP,
  NODE_DATA                      TYPE STRING VALUE 'NODE_DATA',
  INVOICEID                      TYPE STRING VALUE 'INVOICEID',
  PAID                           TYPE STRING VALUE 'PAID',
  COMMENTS                       TYPE STRING VALUE 'COMMENTS',
      END OF ZS4H_INVOICE_TP,
    END OF SC_NODE_ATTRIBUTE .
  constants:
    BEGIN OF SC_NODE_CATEGORY,
      BEGIN OF ZS4H_INVOICE_TP,
 ROOT                           TYPE /BOBF/OBM_NODE_CAT_KEY VALUE '288023A883C01EE8A9D49B38BEB545CE',
      END OF ZS4H_INVOICE_TP,
    END OF SC_NODE_CATEGORY .
endinterface.
