interface ZIF_S4H_C_EMPLOYEE_C
  public .


  interfaces /BOBF/IF_LIB_CONSTANTS .

  constants:
    BEGIN OF SC_ACTION,
      BEGIN OF ZS4H_C_EMPLOYEE,
 CREATE_ZS4H_C_EMPLOYEE         TYPE /BOBF/ACT_KEY VALUE '288023A883C01EE8AAE667B36EC5C16A',
 DELETE_ZS4H_C_EMPLOYEE         TYPE /BOBF/ACT_KEY VALUE '288023A883C01EE8AAE667B36EC6416A',
 LOCK_ZS4H_C_EMPLOYEE           TYPE /BOBF/ACT_KEY VALUE '288023A883C01EE8AAE6678D3A49A16A',
 SAVE_ZS4H_C_EMPLOYEE           TYPE /BOBF/ACT_KEY VALUE '288023A883C01EE8AAE667B36EC6C16A',
 UNLOCK_ZS4H_C_EMPLOYEE         TYPE /BOBF/ACT_KEY VALUE '288023A883C01EE8AAE6678D3A49E16A',
 UPDATE_ZS4H_C_EMPLOYEE         TYPE /BOBF/ACT_KEY VALUE '288023A883C01EE8AAE667B36EC6016A',
 VALIDATE_ZS4H_C_EMPLOYEE       TYPE /BOBF/ACT_KEY VALUE '288023A883C01EE8AAE667B36EC6816A',
      END OF ZS4H_C_EMPLOYEE,
    END OF SC_ACTION .
  constants:
    BEGIN OF SC_ACTION_ATTRIBUTE,
        BEGIN OF ZS4H_C_EMPLOYEE,
        BEGIN OF LOCK_ZS4H_C_EMPLOYEE,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
        END OF LOCK_ZS4H_C_EMPLOYEE,
        BEGIN OF UNLOCK_ZS4H_C_EMPLOYEE,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
        END OF UNLOCK_ZS4H_C_EMPLOYEE,
      END OF ZS4H_C_EMPLOYEE,
    END OF SC_ACTION_ATTRIBUTE .
  constants:
    BEGIN OF SC_ASSOCIATION,
      BEGIN OF ZS4H_C_EMPLOYEE,
 LOCK                           TYPE /BOBF/OBM_ASSOC_KEY VALUE '288023A883C01EE8AAE6678D3A49816A',
 MESSAGE                        TYPE /BOBF/OBM_ASSOC_KEY VALUE '288023A883C01EE8AAE6678D3A49416A',
 PROPERTY                       TYPE /BOBF/OBM_ASSOC_KEY VALUE '288023A883C01EE8AAE6678D3A4A416A',
      END OF ZS4H_C_EMPLOYEE,
      BEGIN OF ZS4H_C_EMPLOYEE_LOCK,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '288023A883C01EE8AAE667B36EC7216A',
      END OF ZS4H_C_EMPLOYEE_LOCK,
      BEGIN OF ZS4H_C_EMPLOYEE_MESSAGE,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '288023A883C01EE8AAE667B36EC7016A',
      END OF ZS4H_C_EMPLOYEE_MESSAGE,
      BEGIN OF ZS4H_C_EMPLOYEE_PROPERTY,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '288023A883C01EE8AAE667B36EC7416A',
      END OF ZS4H_C_EMPLOYEE_PROPERTY,
    END OF SC_ASSOCIATION .
  constants:
    BEGIN OF SC_ASSOCIATION_ATTRIBUTE,
      BEGIN OF ZS4H_C_EMPLOYEE,
        BEGIN OF PROPERTY,
 ALL_NODE_PROPERTY              TYPE STRING VALUE 'ALL_NODE_PROPERTY',
 ALL_NODE_ATTRIBUTE_PROPERTY    TYPE STRING VALUE 'ALL_NODE_ATTRIBUTE_PROPERTY',
 ALL_ASSOCIATION_PROPERTY       TYPE STRING VALUE 'ALL_ASSOCIATION_PROPERTY',
 ALL_ASSOCIATION_ATTRIBUTE_PROP TYPE STRING VALUE 'ALL_ASSOCIATION_ATTRIBUTE_PROP',
 ALL_ACTION_PROPERTY            TYPE STRING VALUE 'ALL_ACTION_PROPERTY',
 ALL_ACTION_ATTRIBUTE_PROPERTY  TYPE STRING VALUE 'ALL_ACTION_ATTRIBUTE_PROPERTY',
 ALL_QUERY_PROPERTY             TYPE STRING VALUE 'ALL_QUERY_PROPERTY',
 ALL_QUERY_ATTRIBUTE_PROPERTY   TYPE STRING VALUE 'ALL_QUERY_ATTRIBUTE_PROPERTY',
 ALL_SUBTREE_PROPERTY           TYPE STRING VALUE 'ALL_SUBTREE_PROPERTY',
        END OF PROPERTY,
      END OF ZS4H_C_EMPLOYEE,
    END OF SC_ASSOCIATION_ATTRIBUTE .
  constants:
    SC_BO_KEY  TYPE /BOBF/OBM_BO_KEY VALUE '288023A883C01EE8AAE6678D3A48A16A' .
  constants:
    SC_BO_NAME TYPE /BOBF/OBM_NAME VALUE 'ZS4H_C_EMPLOYEE' .
  constants:
    BEGIN OF SC_DETERMINATION,
      BEGIN OF ZS4H_C_EMPLOYEE,
 ACTION_AND_FIELD_CONTROL       TYPE /BOBF/DET_KEY VALUE '288023A883C01EE8AAE667B36EC7A16A',
      END OF ZS4H_C_EMPLOYEE,
    END OF SC_DETERMINATION .
  constants:
    SC_MODEL_VERSION TYPE /BOBF/CONF_VERSION VALUE '00000' .
  constants:
    BEGIN OF SC_NODE,
 ZS4H_C_EMPLOYEE                TYPE /BOBF/OBM_NODE_KEY VALUE '288023A883C01EE8AAE6678D3A48E16A',
 ZS4H_C_EMPLOYEE_LOCK           TYPE /BOBF/OBM_NODE_KEY VALUE '288023A883C01EE8AAE6678D3A49616A',
 ZS4H_C_EMPLOYEE_MESSAGE        TYPE /BOBF/OBM_NODE_KEY VALUE '288023A883C01EE8AAE6678D3A49216A',
 ZS4H_C_EMPLOYEE_PROPERTY       TYPE /BOBF/OBM_NODE_KEY VALUE '288023A883C01EE8AAE6678D3A4A216A',
    END OF SC_NODE .
  constants:
    BEGIN OF SC_NODE_ATTRIBUTE,
      BEGIN OF ZS4H_C_EMPLOYEE,
  NODE_DATA                      TYPE STRING VALUE 'NODE_DATA',
  EMPLOYEE_ID                    TYPE STRING VALUE 'EMPLOYEE_ID',
  FIRST_NAME                     TYPE STRING VALUE 'FIRST_NAME',
  MIDDLE_NAME                    TYPE STRING VALUE 'MIDDLE_NAME',
  LAST_NAME                      TYPE STRING VALUE 'LAST_NAME',
  INITIALS                       TYPE STRING VALUE 'INITIALS',
  SEX                            TYPE STRING VALUE 'SEX',
  LANGUAGE                       TYPE STRING VALUE 'LANGUAGE',
  PHONE_NUMBER                   TYPE STRING VALUE 'PHONE_NUMBER',
  FAX_NUMBER                     TYPE STRING VALUE 'FAX_NUMBER',
  MOBILE_NUMBER                  TYPE STRING VALUE 'MOBILE_NUMBER',
  EMAIL_ADDRESS                  TYPE STRING VALUE 'EMAIL_ADDRESS',
  LOGIN_NAME                     TYPE STRING VALUE 'LOGIN_NAME',
  PR_ADDRESS_GUID                TYPE STRING VALUE 'PR_ADDRESS_GUID',
  VAL_START_DATE                 TYPE STRING VALUE 'VAL_START_DATE',
  VAL_END_DATE                   TYPE STRING VALUE 'VAL_END_DATE',
  CURRENCY                       TYPE STRING VALUE 'CURRENCY',
  SALARY_AMOUNT                  TYPE STRING VALUE 'SALARY_AMOUNT',
  ACCOUNT_NUMBER                 TYPE STRING VALUE 'ACCOUNT_NUMBER',
  BANK_ID                        TYPE STRING VALUE 'BANK_ID',
  BANK_NAME                      TYPE STRING VALUE 'BANK_NAME',
  EMPLOYEE_PIC_URL               TYPE STRING VALUE 'EMPLOYEE_PIC_URL',
      END OF ZS4H_C_EMPLOYEE,
    END OF SC_NODE_ATTRIBUTE .
  constants:
    BEGIN OF SC_NODE_CATEGORY,
      BEGIN OF ZS4H_C_EMPLOYEE,
 ROOT                           TYPE /BOBF/OBM_NODE_CAT_KEY VALUE '288023A883C01EE8AAE6678D3A49016A',
      END OF ZS4H_C_EMPLOYEE,
    END OF SC_NODE_CATEGORY .
endinterface.
