interface ZIF_DEV_SALESORDER_TX_D_C
  public .


  interfaces /BOBF/IF_LIB_CONSTANTS .

  constants:
    BEGIN OF SC_ACTION,
      BEGIN OF ZDEV_SALESORDER_TX_D,
 ACTIVATION                     TYPE /BOBF/ACT_KEY VALUE '288023A883C01EE8ADD534C7470044B7',
 CREATE_ZDEV_SALESORDER_TX_D    TYPE /BOBF/ACT_KEY VALUE '288023A883C01EE8ADD5341DFA2384B6',
 DELETE_ZDEV_SALESORDER_TX_D    TYPE /BOBF/ACT_KEY VALUE '288023A883C01EE8ADD5341DFA2404B6',
 EDIT                           TYPE /BOBF/ACT_KEY VALUE '288023A883C01EE8ADD534C7470024B7',
 LOCK_ZDEV_SALESORDER_TX_D      TYPE /BOBF/ACT_KEY VALUE '288023A883C01EE8ADD5341DFA22C4B6',
 PREPARATION                    TYPE /BOBF/ACT_KEY VALUE '288023A883C01EE8ADD534C7470084B7',
 SAVE_ZDEV_SALESORDER_TX_D      TYPE /BOBF/ACT_KEY VALUE '288023A883C01EE8ADD5341DFA2484B6',
 UNLOCK_ZDEV_SALESORDER_TX_D    TYPE /BOBF/ACT_KEY VALUE '288023A883C01EE8ADD5341DFA2304B6',
 UPDATE_ZDEV_SALESORDER_TX_D    TYPE /BOBF/ACT_KEY VALUE '288023A883C01EE8ADD5341DFA23C4B6',
 VALIDATE_ZDEV_SALESORDER_TX_D  TYPE /BOBF/ACT_KEY VALUE '288023A883C01EE8ADD5341DFA2444B6',
 VALIDATION                     TYPE /BOBF/ACT_KEY VALUE '288023A883C01EE8ADD534C7470064B7',
      END OF ZDEV_SALESORDER_TX_D,
    END OF SC_ACTION .
  constants:
    BEGIN OF SC_ACTION_ATTRIBUTE,
        BEGIN OF ZDEV_SALESORDER_TX_D,
        BEGIN OF EDIT,
 PRESERVE_CHANGES               TYPE STRING VALUE 'PRESERVE_CHANGES',
        END OF EDIT,
        BEGIN OF LOCK_ZDEV_SALESORDER_TX_D,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
        END OF LOCK_ZDEV_SALESORDER_TX_D,
        BEGIN OF PREPARATION,
 SIDEEFFECTSQUALIFIER           TYPE STRING VALUE 'SIDEEFFECTSQUALIFIER',
        END OF PREPARATION,
        BEGIN OF UNLOCK_ZDEV_SALESORDER_TX_D,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
        END OF UNLOCK_ZDEV_SALESORDER_TX_D,
        BEGIN OF VALIDATION,
 SIDEEFFECTSQUALIFIER           TYPE STRING VALUE 'SIDEEFFECTSQUALIFIER',
        END OF VALIDATION,
      END OF ZDEV_SALESORDER_TX_D,
    END OF SC_ACTION_ATTRIBUTE .
  constants:
    BEGIN OF SC_ALTERNATIVE_KEY,
      BEGIN OF ZDEV_SALESORDER_TX_D,
 ACTIVE_ENTITY_KEY              TYPE /BOBF/OBM_ALTKEY_KEY VALUE '288023A883C01EE8ADD534C7470004B7',
      END OF ZDEV_SALESORDER_TX_D,
    END OF SC_ALTERNATIVE_KEY .
  constants:
    BEGIN OF SC_ASSOCIATION,
      BEGIN OF ZDEV_SALESORDER_TX_D,
 LOCK                           TYPE /BOBF/OBM_ASSOC_KEY VALUE '288023A883C01EE8ADD5341DFA22A4B6',
 MESSAGE                        TYPE /BOBF/OBM_ASSOC_KEY VALUE '288023A883C01EE8ADD5341DFA2264B6',
 PROPERTY                       TYPE /BOBF/OBM_ASSOC_KEY VALUE '288023A883C01EE8ADD5341DFA2364B6',
      END OF ZDEV_SALESORDER_TX_D,
      BEGIN OF ZDEV_SALESORDER_TX_D_LOCK,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '288023A883C01EE8ADD5341DFA24E4B6',
      END OF ZDEV_SALESORDER_TX_D_LOCK,
      BEGIN OF ZDEV_SALESORDER_TX_D_MESSAGE,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '288023A883C01EE8ADD5341DFA24C4B6',
      END OF ZDEV_SALESORDER_TX_D_MESSAGE,
      BEGIN OF ZDEV_SALESORDER_TX_D_PROPERTY,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '288023A883C01EE8ADD5341DFA2504B6',
      END OF ZDEV_SALESORDER_TX_D_PROPERTY,
    END OF SC_ASSOCIATION .
  constants:
    BEGIN OF SC_ASSOCIATION_ATTRIBUTE,
      BEGIN OF ZDEV_SALESORDER_TX_D,
        BEGIN OF PROPERTY,
 ALL_NODE_PROPERTY              TYPE STRING VALUE 'ALL_NODE_PROPERTY',
 ALL_NODE_ATTRIBUTE_PROPERTY    TYPE STRING VALUE 'ALL_NODE_ATTRIBUTE_PROPERTY',
 ALL_ASSOCIATION_PROPERTY       TYPE STRING VALUE 'ALL_ASSOCIATION_PROPERTY',
 ALL_ASSOCIATION_ATTRIBUTE_PROP TYPE STRING VALUE 'ALL_ASSOCIATION_ATTRIBUTE_PROP',
 ALL_ACTION_PROPERTY            TYPE STRING VALUE 'ALL_ACTION_PROPERTY',
 ALL_ACTION_ATTRIBUTE_PROPERTY  TYPE STRING VALUE 'ALL_ACTION_ATTRIBUTE_PROPERTY',
 ALL_QUERY_PROPERTY             TYPE STRING VALUE 'ALL_QUERY_PROPERTY',
 ALL_QUERY_ATTRIBUTE_PROPERTY   TYPE STRING VALUE 'ALL_QUERY_ATTRIBUTE_PROPERTY',
 ALL_SUBTREE_PROPERTY           TYPE STRING VALUE 'ALL_SUBTREE_PROPERTY',
        END OF PROPERTY,
      END OF ZDEV_SALESORDER_TX_D,
    END OF SC_ASSOCIATION_ATTRIBUTE .
  constants:
    SC_BO_KEY  TYPE /BOBF/OBM_BO_KEY VALUE '288023A883C01EE8ADD5341DFA21C4B6' .
  constants:
    SC_BO_NAME TYPE /BOBF/OBM_NAME VALUE 'ZDEV_SALESORDER_TX_D' .
  constants:
    BEGIN OF SC_DETERMINATION,
      BEGIN OF ZDEV_SALESORDER_TX_D,
 ACTION_AND_FIELD_CONTROL       TYPE /BOBF/DET_KEY VALUE '288023A883C01EE8ADD534C74700A4B7',
 CENTRAL_ADMIN_DATA             TYPE /BOBF/DET_KEY VALUE '288023A883C01EE8ADD534C74700C4B7',
 DELETE_DRAFT_WHN_ACTIVE_DELETE TYPE /BOBF/DET_KEY VALUE '288023A883C01EE8ADD534C74701A4B7',
 DRAFT_ACTION_CONTROL           TYPE /BOBF/DET_KEY VALUE '288023A883C01EE8ADD534C7470184B7',
 DRAFT_SYS_ADMIN_DATA           TYPE /BOBF/DET_KEY VALUE '288023A883C01EE8ADD534C74700E4B7',
 DURABLE_LOCK_CLEANUP_CLEANUP   TYPE /BOBF/DET_KEY VALUE '288023A883C01EE8ADD534C7470164B7',
 DURABLE_LOCK_CLEANUP_DELETE    TYPE /BOBF/DET_KEY VALUE '288023A883C01EE8ADD534C7470104B7',
 DURABLE_LOCK_CLEANUP_FAIL_SAVE TYPE /BOBF/DET_KEY VALUE '288023A883C01EE8ADD534C7470144B7',
 DURABLE_LOCK_CLEANUP_SUCC_SAVE TYPE /BOBF/DET_KEY VALUE '288023A883C01EE8ADD534C7470124B7',
      END OF ZDEV_SALESORDER_TX_D,
    END OF SC_DETERMINATION .
  constants:
    BEGIN OF SC_GROUP,
 DRAFT_CONSISTENCY              TYPE /BOBF/OBM_GROUP_KEY VALUE '288023A883C01EE8ADD534C746FFA4B7',
    END OF SC_GROUP .
  constants:
    SC_MODEL_VERSION TYPE /BOBF/CONF_VERSION VALUE '00000' .
  constants:
    BEGIN OF SC_NODE,
 ZDEV_SALESORDER_TX_D           TYPE /BOBF/OBM_NODE_KEY VALUE '288023A883C01EE8ADD5341DFA2204B6',
 ZDEV_SALESORDER_TX_D_LOCK      TYPE /BOBF/OBM_NODE_KEY VALUE '288023A883C01EE8ADD5341DFA2284B6',
 ZDEV_SALESORDER_TX_D_MESSAGE   TYPE /BOBF/OBM_NODE_KEY VALUE '288023A883C01EE8ADD5341DFA2244B6',
 ZDEV_SALESORDER_TX_D_PROPERTY  TYPE /BOBF/OBM_NODE_KEY VALUE '288023A883C01EE8ADD5341DFA2344B6',
    END OF SC_NODE .
  constants:
    BEGIN OF SC_NODE_ATTRIBUTE,
      BEGIN OF ZDEV_SALESORDER_TX_D,
  NODE_DATA                      TYPE STRING VALUE 'NODE_DATA',
  SALESORDER                     TYPE STRING VALUE 'SALESORDER',
  BUSINESSPARTNER                TYPE STRING VALUE 'BUSINESSPARTNER',
  OVERALLSTATUS                  TYPE STRING VALUE 'OVERALLSTATUS',
  ACTIVEUUID                     TYPE STRING VALUE 'ACTIVEUUID',
  HASACTIVEENTITY                TYPE STRING VALUE 'HASACTIVEENTITY',
  DRAFTENTITYCREATIONDATETIME    TYPE STRING VALUE 'DRAFTENTITYCREATIONDATETIME',
  DRAFTENTITYLASTCHANGEDATETIME  TYPE STRING VALUE 'DRAFTENTITYLASTCHANGEDATETIME',
  DRAFTENTITYCONSISTENCYSTATUS   TYPE STRING VALUE 'DRAFTENTITYCONSISTENCYSTATUS',
  ISACTIVEENTITY                 TYPE STRING VALUE 'ISACTIVEENTITY',
      END OF ZDEV_SALESORDER_TX_D,
    END OF SC_NODE_ATTRIBUTE .
  constants:
    BEGIN OF SC_NODE_CATEGORY,
      BEGIN OF ZDEV_SALESORDER_TX_D,
 ROOT                           TYPE /BOBF/OBM_NODE_CAT_KEY VALUE '288023A883C01EE8ADD5341DFA2224B6',
      END OF ZDEV_SALESORDER_TX_D,
    END OF SC_NODE_CATEGORY .
  constants:
    BEGIN OF SC_STATUS_VARIABLE,
      BEGIN OF ZDEV_SALESORDER_TX_D,
 DRAFT_CONSISTENCY_STATUS       TYPE /BOBF/STA_VAR_KEY VALUE '288023A883C01EE8ADD534C746FF84B7',
      END OF ZDEV_SALESORDER_TX_D,
    END OF SC_STATUS_VARIABLE .
  constants:
    BEGIN OF SC_VALIDATION,
      BEGIN OF ZDEV_SALESORDER_TX_D,
 DURABLE_LOCK_CREATE_FOR_NEW    TYPE /BOBF/VAL_KEY VALUE '288023A883C01EE8ADD534C74701C4B7',
      END OF ZDEV_SALESORDER_TX_D,
    END OF SC_VALIDATION .
endinterface.
